# vim:set ft=tmux:
%hidden MODULE_NAME="git_branch"

set -gq "@catppuccin_${MODULE_NAME}_icon" " "
set -gqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_teal}"
set -gq "@catppuccin_${MODULE_NAME}_text" " #(~/.tmux/custom/git_status.sh #{pane_current_path})"

source "~/.tmux/plugins/tmux/utils/status_module.conf"
